### ISSUE TITLE
Sort the exams in the drive to Moadim automatically

### ISSUE THREAD

**Issue by yuvalron** [TechnionYP5779/Testock#11]
Need to generate a script which receives a directory (i.e. from the faculty drive), and sorts it as follows
![image](https://user-images.githubusercontent.com/28152692/49685614-b9bafd00-faee-11e8-9cee-8dbe16c680ed.png)

**Comment by menhel** [comment]
@maxcalderon1997 write a python script that outputs all the exams in the drive in the above format.
If you need more clarification, please contact me or @yuvalron

**Comment by maxcalderon1997** [comment]
> @maxcalderon1997 write a python script that outputs all the exams in the drive in the above format.
> If you need more clarification, please contact me or @yuvalron

[https://drive.google.com/open?id=1-HwISeznG280c6MGcIA70X2Me6gemScW
](url)

here you can download the output of my script and my script.

**the files in that zip are:**
- orderExams.py - the main script. it recieves a directory and outputs a new directory with all the exams from the input directory, and changes their names according to the ug format. also it exctracts all the zip files to a directory called "extracted".
- orderExamsCheck.py - a testing script. it creates a directory with empty files with the names of the exams and the new names.
- outProblems.txt - the names of the files which aren't exams or the script couldn't resolve their name.
- outCheckProblems.txt - same, but for the test script
- convert_all_jpg_to_pdf.py - a script that recieves a directory and creates a new one with copies of all the gpg files in the input directory, converted to pdfs.
- convert_all_doc_x_to_pdf.py - same, but for doc or docx files.
- out - the output of the main script.
- outCheck - the output of the test script.

**i got these outputs from an input directory that i created from the technion CS drive and the outputs of the other scripts listed above.**

**Comment by maxcalderon1997** [comment]
@menhel please notify me when someone downloads this, so i can delete it from my drive

**Comment by ron4548** [comment]
@maxcalderon1997 Please upload the scripts to a separate location in case we want to see just the code - it is more important than the content itself.
