### ISSUE TITLE
Find customer

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#110]
We need to find a customer that will work with us in agile process.
Need to check if one of these ASAT positions can help us:
![image](https://user-images.githubusercontent.com/4895877/50458245-3b71ae00-096a-11e9-9315-26f4a012df61.png)
Another option is to find students that will want to do it.

**Comment by ron4548** [comment]
@yuvalron Please update

**Comment by ron4548** [comment]
@yuvalron Please update

**Comment by yuvalron** [comment]
Our customer will be the Students' Committee of our faculty.

Tomorrow is our first meeting.
