### ISSUE TITLE
Cloud function to generate PDF fails

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#119]
For example the following link:
https://us-central1-yp5779-testock.cloudfunctions.net/getPDFofExam?course=234293&year=2016&semester=winter&moed=B
Need to figure out why. Firebase log says: response error without any exception.

**Comment by ameeramer** [comment]
I'm running the function locally and getting this error - unknown image format. 

![image](https://user-images.githubusercontent.com/19497043/50487229-12066000-0a06-11e9-8e05-a053064a086b.png)

**Comment by ameeramer** [comment]
This is what shows up in the firebase console too, though only yesterday.

![image](https://user-images.githubusercontent.com/19497043/50487287-5b56af80-0a06-11e9-8e7c-34d4f0d4fbc9.png)

**Comment by ron4548** [comment]
This error was because a user uploaded an empty image. The current error with the link I provided is:
![image](https://user-images.githubusercontent.com/4895877/50487390-e9cb3100-0a06-11e9-8a5a-a01259d15087.png)

**Comment by ron4548** [comment]
@ameeramer found that this problem was indeed because someone uploaded an empty image. We had to manually delete the entry from the DB until we will implement a check that the image is not empty.
Anyway, we couldn't find more empty images, but we assume there might be some more. In case something is found, reopen this issue.
