### ISSUE TITLE
Feature: Add option to clean pages from upload page

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#124]
In every scan there are unnecessary pages. We want to allow the user to discard these pages before he start selecting the questions.
We should also add a button "Discard first page", "Discard all even pages" and "Discard all odd pages" since this is a very common scenario in scans.

**Comment by menhel** [comment]
Right now, removing pages is an action we cannot undo, this is not the desired behavior. It should function as a filter, rather than an action.

**Comment by ron4548** [comment]
@menhel Better than nothing.

**Comment by menhel** [comment]
Might be, but we decided we will put this topic on hold for now, and focus on other issues.
