### ISSUE TITLE
Safot: get DB from the website's admins

### ISSUE THREAD

**Issue by yuvalron** [TechnionYP5779/Testock#13]

**Comment by yuvalron** [comment]
DB on telegram

**Comment by maxcalderon1997** [comment]
> DB on telegram

you can also find the important tables from that DB in csv format here:
https://drive.google.com/drive/folders/1zjh39p5OR9EtuEb8vsioKNpVryUNdIgv?usp=sharing

all that's left is to write a script that reads the data from the CSV files and put it in firebase
