### ISSUE TITLE
wrong years in ug scans name format

### ISSUE THREAD

**Issue by maxcalderon1997** [TechnionYP5779/Testock#131]
the correct year is 1 + the year in the ug scan name

**Comment by ameeramer** [comment]
@ron4548

**Comment by ron4548** [comment]
@menhel We need to discuss it. The problem: Technion scan file name (and bar codes) mark the current semester as Spring 2018. Students, however, refer to the current semester as Spring 2019.

**Comment by ron4548** [comment]
I talked to Saar about it. We should display the semesters like in the web course.
Current semester: Spring 2019
Previous semester: Winter 2018-2019
