### ISSUE TITLE
roles: try to find service that implements roles

### ISSUE THREAD

**Issue by maxcalderon1997** [TechnionYP5779/Testock#132]
roles: guest, user, faculty-admin, superuser.
capabilities: view, upload, edit (your scan, faculty scans, other), delete (your scan, faculty scans, other), edit_roles.
**capability of each role:**
- guest: view.
- user: view, upload, edit your scan.
- faculty-admin: view, upload, edit your scan, delete your scan.
- superuser: can do everything except for beating goku in a fight.

**Comment by ron4548** [comment]
I think that we can implement it, it shouldn't be that hard.
https://angularfirebase.com/lessons/role-based-authorization-with-firestore-nosql-and-angular-5/

**Comment by ron4548** [comment]
Done with #150
