### ISSUE TITLE
roles: block upload pages for guests

### ISSUE THREAD

**Issue by maxcalderon1997** [TechnionYP5779/Testock#133]

**Comment by ron4548** [comment]
I have previously checked how to implement such things. This can be very helpful:
https://angularfirebase.com/lessons/role-based-authorization-with-firestore-nosql-and-angular-5/

**Comment by menhel** [comment]
This looks like exactly what we need. You may proceed with the implementation of this :-)

**Comment by ron4548** [comment]
Done with #150
