### ISSUE TITLE
add option to edit scan/question

### ISSUE THREAD

**Issue by maxcalderon1997** [TechnionYP5779/Testock#136]

**Comment by ron4548** [comment]
Edit solution (grade only) is done with #150

**Comment by ron4548** [comment]
@menhel Please add UI for question editing. Couldn't come up with a good idea where to put it.
I thought to make it like inline edit but couldn't find good component for that. We can do it with modal like I did with solutions editing.

**Comment by menhel** [comment]
A Modal is just fine for now. Let's see if the client will have any rejects and we will update it if necessary.
Closed for now.
