### ISSUE TITLE
discussions: tinymce/other text editor- find component

### ISSUE THREAD

**Issue by maxcalderon1997** [TechnionYP5779/Testock#141]

**Comment by ron4548** [comment]
Maybe https://www.npmjs.com/package/ngx-editor?

**Comment by maxcalderon1997** [comment]
@ron4548 @menhel so what do you think is better? npmjs or tinymce?

**Comment by ron4548** [comment]
https://www.npmjs.com/package/ngx-ckeditor
Installed this, working on create topic component.
