### ISSUE TITLE
discussions UI: add a page for each question and all it's answers

### ISSUE THREAD

**Issue by maxcalderon1997** [TechnionYP5779/Testock#142]

**Comment by ron4548** [comment]
@menhel I am not sure what this issue means. Can you add a description?

**Comment by maxcalderon1997** [comment]
> @menhel I am not sure what this issue means. Can you add a description?

it's like safot website- there's a page for each question and all it's answers

**Comment by ron4548** [comment]
@maxcalderon1997 Thanks

**Comment by yuvalron** [comment]
The term question is confusing since there is already questions in exams

**Comment by menhel** [comment]
I agree. Let's use "discussion topic" instead. Or maybe even "Topic" and "Reply".

**Comment by ron4548** [comment]
Topic or Thread are better terms.

**Comment by ron4548** [comment]
@yuvalron Please use the following routing scheme:
/topic/:id where id is the id of the topic
