### ISSUE TITLE
Convert Observables usage throughout all the project

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#148]
Seems like we used a bad design with the observables. Instead of subscribing to the observable and update a local field with the result, we should save the observable itself in a field, and then use the async pipe within the HTML whenever we need to result of the observable.
See last example here: https://angular.io/api/common/AsyncPipe
The correct design should prevent memory leaks and save resources...

**Comment by menhel** [comment]
Closed

**Comment by menhel** [comment]
Halas
