### ISSUE TITLE
Chrome Plugin: Add close button for popup

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/Testock#157]
add a little X in the popup to close it, in case it bothers the user.

**Comment by ameeramer** [comment]
this commit closes it 85b0578dc9e42b8ffde68d55b01a20f1a8d52302

**Comment by ameeramer** [comment]
![image](https://user-images.githubusercontent.com/19497043/51317982-b279fe00-1a61-11e9-96cd-7ecb8d9f8594.png)
