### ISSUE TITLE
Initial Template Wireframes

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/Testock#16]
Need to create a wireframes for the following pages:
1. exam upload - the users uploads it's exam to the website
2. pages selection - after the user uploads the exam, the system will show him an image of every page. now he needs to select which pages he wants to keep, and which pages he wants to delete
3. edited exam view - see the result of the output exam (I guess it should be a PDF version of it already)
4. all exams - for now, a page that contains links to all exams in the DB. later, we will change the meaning of this page. keep it as generic a possible (maybe we will use this template to show not only exams, maybe faculties, etc.)

Notes:
1. All wireframes should take into account the components available to us in the [Bootstrap](https://getbootstrap.com/docs/4.1/getting-started/introduction/) module we implemented. See the Layout and Components sections on the left menu in the link. Make sure you don't wireframes we can't implement.
2. In a nutshell, bootstrap divides the website into 12 columns. Each element in the website can take 1/12 to 12/12 parts of the website width. So it is really easy to create a 4 elements grid, like a gallery in which we have 4 images in a row. Take this into consideration and read the bootstrap documentation before you start
3. I am a little bit familiar with Bootstrap, so if you have any questions, contact me :-)

Good Luck!

**Comment by yuvalron** [comment]
Draft:

all exams
![image](https://user-images.githubusercontent.com/19504086/50087375-8708b700-0208-11e9-81e1-b1c36fb366dc.png)


![image](https://user-images.githubusercontent.com/19504086/50087413-a99ad000-0208-11e9-9c5c-c169c91be846.png)


![image](https://user-images.githubusercontent.com/19504086/50087417-ad2e5700-0208-11e9-8a57-388877a1b1ad.png)


![image](https://user-images.githubusercontent.com/19504086/50087422-b0c1de00-0208-11e9-9d5b-b2527ab1466e.png)


![image](https://user-images.githubusercontent.com/19504086/50087425-b3243800-0208-11e9-99a9-3b9e88bbf76b.png)
