### ISSUE TITLE
Discussions: add comments count

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#173]
Since Firestore doesn't support counts queries we should maintain a counter within the topic document and update it with transactions or with cloud functions.

**Comment by maxcalderon1997** [comment]
> Since Firestore doesn't support counts queries we should maintain a counter within the topic document and update it with transactions or with cloud functions.

@ron4548 do you think something like (comments$ | async as comments) and then comments.length should work?

**Comment by ron4548** [comment]
> > Since Firestore doesn't support counts queries we should maintain a counter within the topic document and update it with transactions or with cloud functions.
> 
> @ron4548 do you think something like (comments$ | async as comments) and then comments.length should work?

Yes, but it is very inefficient and with high probability for memory leaks.

**Comment by maxcalderon1997** [comment]
> > > Since Firestore doesn't support counts queries we should maintain a counter within the topic document and update it with transactions or with cloud functions.
> > 
> > 
> > @ron4548 do you think something like (comments$ | async as comments) and then comments.length should work?
> 
> Yes, but it is very inefficient and with high probability for memory leaks.

i saw this usage in course component:
![image](https://user-images.githubusercontent.com/19844997/51558456-27956b00-1e88-11e9-87fe-042c7f833f77.png)

**Comment by ron4548** [comment]
> > > > Since Firestore doesn't support counts queries we should maintain a counter within the topic document and update it with transactions or with cloud functions.
> > > 
> > > 
> > > @ron4548 do you think something like (comments$ | async as comments) and then comments.length should work?
> > 
> > 
> > Yes, but it is very inefficient and with high probability for memory leaks.
> 
> i saw this kind of usage in course component:
> ![image](https://user-images.githubusercontent.com/19844997/51558456-27956b00-1e88-11e9-87fe-042c7f833f77.png)

It is bad implementation. But for comments count you need to perform query for each topic in the list, this is very heavy.
