### ISSUE TITLE
remove title input from comment form

### ISSUE THREAD

**Issue by maxcalderon1997** [TechnionYP5779/Testock#191]
![image](https://user-images.githubusercontent.com/19844997/51498587-bd20f400-1dcf-11e9-85a4-39f63c23a021.png)

**Comment by ron4548** [comment]
This issue should be converted to “remove title input from comment form”

**Comment by maxcalderon1997** [comment]
> This issue should be converted to “remove title input from comment form”

@ron4548 why not enable title for comments?

**Comment by maxcalderon1997** [comment]
fixed with fa3f7a1
