### ISSUE TITLE
Fix website breadcrumb

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/Testock#20]
Right now, the data shown is static. Make sure the breadcrumb shown corresponds to the actual location in the website

You might find this helpful (you also might not):
https://brianflove.com/2016/10/23/angular2-breadcrumb-using-router/

**Comment by yuvalron** [comment]
> The above tutorial has some disadvantages since it is not totally dynamic.
> 
> I've found this one: https://github.com/gmostert/ng2-breadcrumb
> With a live example: https://www.theticketresale.com/movies/1349

Not working on Angular 6+

**Comment by yuvalron** [comment]
Tring this one: https://www.npmjs.com/package/ng6-breadcrumbs

**Comment by menhel** [comment]
> The above tutorial is not good since it is not dynamic.
> 
> For example when the router path is: 'course/:id'
> we would like the breadcrumb to show: 'course/23652' based on the dynamic value of id.
> But in this tutorial, you can only assign a static string.

Can we solve this problem with some extra code? somehow getting the id, and writing the desired string?

**Comment by yuvalron** [comment]
Answer from the author:

![image](https://user-images.githubusercontent.com/19504086/50348026-509ca600-0540-11e9-81b7-3bb86e3acae8.png)

**Comment by ron4548** [comment]
Just saying (didn't read the links you attached): The router object is injectable and should be accessible from all components to get the currently activated route.
