### ISSUE TITLE
Remove pages buttons functionality is incomplete

### ISSUE THREAD

**Issue by yuvalron** [TechnionYP5779/Testock#200]
- bug: when pressing the "remove even pages" more than one it continues to delete pages.
- the user should be able to select "remove even pages" and "remove first page".
- when pressing the "remove even pages" and then the "remove odd pages", the result should be that the even pages are returned and only the original odd pages will be deleted.
- and of course, an option to return to the original state.

**Comment by ron4548** [comment]
It wasn't part of sprint2 anyway, so I added only basic functionality. When our customer will say we will make it more stable.
