### ISSUE TITLE
Add title page extraction from scan

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#212]
We might want to consider the following enhancement for the upload process: when uploading a scan, first ask the user where is the title page of the scan where the grades for each question appears. Then ask him how much he got for each question and then let him select the solutions without having to check the grade for each question separately.

**Comment by menhel** [comment]
@yuvalron @ron4548 
How about taking it on next week? Seems important

**Comment by ron4548** [comment]
@menhel Need to discuss it with Saar and the rest of the team. We also need to decide what is the exact specification for this feature.
