### ISSUE TITLE
Gamification: Define a Reward Scheme

### ISSUE THREAD

**Issue by yuvalron** [TechnionYP5779/Testock#217]
We need to define which actions will be counted in our reward scheme and by how many points. 
This should motivate our users to contribute to our database.

**Comment by yuvalron** [comment]
I thought about the following scheme:

- Each user starts with 100 points.

Uploading an exam with grade (detailed upload) X: **150 + X points**
Uploading an exam with grade (fast upload) X: **100 + X points**
- A bonus of **50 points** will be given for uploading a scan of a test without any solutions

Opening a new issue: **5 points**
The user's comment was selected as a correct answer: **10 points**
Downloading a scan: **3 points**
Rating a scan's readability: **5 points**
- A bonus of **20 points** will be given to a user which uploaded a scan that has a readability rating of at least 4.0 by 3 different users

**Comment by yuvalron** [comment]
We should consider the case in which a user uploads a scan that is not his. In my opinion, we should add in the upload process a credit field that states who wrote the answers. Most of the times it will be, of course, the uploader itself. There should be also an "unkown" option. If the scan belongs to another user, he will recive points too.

**Comment by menhel** [comment]
I don't think we should award downloading a scan. The purpose of the awarding system is to encourage them to contribute. Downloading is not considered a contribution, but a use.

**Comment by menhel** [comment]
Also, I would raise the award for starting a conversation to 10 points. Updated Scheme:

* Each user starts with 100 points.
* Uploading an exam with grade (detailed upload) X: 150 + X points
* Uploading an exam with grade (fast upload) X: 100 + X points
* A bonus of 50 points will be given for uploading a scan of a test without any solutions
* Opening a new issue: 10 points
* The user's comment was selected as a correct answer: 10 points
* Rating a scan's readability: 5 points

* A bonus of 20 points will be given to a user which uploaded a scan that has a readability rating of at least 4.0 by 3 different users

All other awards look perfect. If you agree, please close the issue.

**Comment by menhel** [comment]
Might be changed later, but good for now. Closing.
