### ISSUE TITLE
Gamification: Define a progression world

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/Testock#220]
For the awarding system to work we need to users to feel that they are advancing. For that, we need to define a progression for our eco-system. 
I though of a world that consists of multiple islands. You progress from one island to another by earning more points (first is 0-300 for example, second is 301-600, etc.).

Inside each islands there are monsters that you can adopt for a payment of points. 

Those ideas needs to be developed (in this US), designed and implements (in other US).

**Comment by ron4548** [comment]
@menhel Not monsters. קמטנים.

**Comment by menhel** [comment]
![image](https://user-images.githubusercontent.com/28152692/55826810-7a8ad000-5b11-11e9-9fc5-53025c86b4e0.png)

**Comment by menhel** [comment]
![image](https://user-images.githubusercontent.com/28152692/55834475-b37f7080-5b22-11e9-9396-3ce3bd2c849a.png)

**Comment by menhel** [comment]
This is enough for now. Closing.
