### ISSUE TITLE
OCR: Use image processing to remove blank pages when uploading scan

### ISSUE THREAD

**Issue by ameeramer** [TechnionYP5779/Testock#221]

**Comment by ameeramer** [comment]
I was able to add logic for removing blank pages, sometimes it detects a non-blank page, need to aff some flag or sign to the user that it is removed so the user can return the page if the classification didn't classify it right.

Moreover, now it takes about 15 seconds to remove the blank pages, since it makes an http request for each page in the solution. Need to find a way to make it faster and/or add a progress bar indicating to the user that it's working.

**Comment by ron4548** [comment]
> I was able to add logic for removing blank pages, sometimes it detects a non-blank page, need to aff some flag or sign to the user that it is removed so the user can return the page if the classification didn't classify it right.
> 
> Moreover, now it takes about 50 seconds to remove the blank pages, since it makes an http request for each page in the solution. Need to find a way to make it faster and/or add a progress bar indicating to the user that it's working.

Have you tried to do all the requests simultaneously? Read about Promise.all, maybe this way it will be faster

**Comment by ameeramer** [comment]
> > I was able to add logic for removing blank pages, sometimes it detects a non-blank page, need to aff some flag or sign to the user that it is removed so the user can return the page if the classification didn't classify it right.
> > Moreover, now it takes about 50 seconds to remove the blank pages, since it makes an http request for each page in the solution. Need to find a way to make it faster and/or add a progress bar indicating to the user that it's working.
> 
> Have you tried to do all the requests simultaneously? Read about Promise.all, maybe this way it will be faster

@ron4548 Worked like a charm!!

**Comment by menhel** [comment]
Can it be closed? @ameeramer
