### ISSUE TITLE
OCR doesn't detect course in some cases

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#222]
![image](https://user-images.githubusercontent.com/4895877/55780904-afffd100-5ab1-11e9-8314-e028f7ff18bc.png)
![image](https://user-images.githubusercontent.com/4895877/55780912-b42bee80-5ab1-11e9-808c-d9d991f56688.png)
[scan-ocr-bug.pdf](https://github.com/TechnionYP5779/Testock/files/3057663/scan-ocr-bug.pdf)

**Comment by ron4548** [comment]
@ameeramer @moshesab This scan is not recognized too
[adasd.pdf](https://github.com/TechnionYP5779/Testock/files/3075053/adasd.pdf)

**Comment by ameeramer** [comment]
fixed in ffbcc1871233f2cd2ee66b62e584cd86b58ba538

**Comment by menhel** [comment]
Can it be closed? @ameeramer @ron4548

**Comment by ameeramer** [comment]
yes. @menhel
