### ISSUE TITLE
Notification: Add push notifications

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/Testock#274]
Popup will show on the website whenever there is a new notification

**Comment by menhel** [comment]
@ron4548 let's talk more about Chrome notifications.

**Comment by ron4548** [comment]
I believe it is built in feature we should use With chrome for example we can gain additional benefit since notifications can work even when the website is not opened.
https://firebase.google.com/docs/cloud-messaging/js/client?authuser=0
