### ISSUE TITLE
Add option to delete questions for faculty admins

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#323]
Cloud functions end:
When a question is deleted, delete all the solutions for it and all topics linked to it. Also need to delete it from solved questions of all users.

**Comment by ameeramer** [comment]
@ron4548 solutions is a collection in question, wouldn't it be deleted automatically?

**Comment by ron4548** [comment]
> @ron4548 solutions is a collection in question, wouldn't it be deleted automatically when the question is deleted?

Wish it would :(
![image](https://user-images.githubusercontent.com/4895877/59046548-e75ce500-888a-11e9-8568-e19943338704.png)

**Comment by ameeramer** [comment]
still need to implement the cloud function end...
