### ISSUE TITLE
Tags: Add option to delete tags from courses and questions

### ISSUE THREAD

**Issue by ameeramer** [TechnionYP5779/Testock#328]

**Comment by ameeramer** [comment]
Do we want to enable users to delete tags of question? if so, users can delete tags of others...

**Comment by ron4548** [comment]
Faculty admins only

**Comment by ameeramer** [comment]
> Faculty admins only

the problem is we give users option to tag questions.. if a user adds a wrong tag, he would want a way to delete it..

**Comment by ron4548** [comment]
I think this feature is not important for now. Admins can assist in case of mistakes. Let's move on to high priority issues.
