### ISSUE TITLE
Header component notifications for guests

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#335]
![image](https://user-images.githubusercontent.com/4895877/58564577-daf6dd80-8235-11e9-9c21-f998e4919e72.png)

**Comment by ron4548** [comment]
@menhel Is this fixed?

**Comment by menhel** [comment]
need to check, dont remember. We'll do it tomorrow.

**Comment by menhel** [comment]
It only occurred the first time the homepage was loaded on logout.
