### ISSUE TITLE
Write a tutorial for using the website

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#338]
This should be ready for the launching. It should include:
- A quick review of all the features
- Tutorial on how to use every feature, especially on how to upload a scan and crop its questions.
It is enough to write it in a Word document. After it will be ready, we will convert it to web page.
To be included in a "Help" page in the website.

**Comment by yuvalron** [comment]
[Testock Help - V1.docx](https://github.com/TechnionYP5779/Testock/files/3288296/Testock.Help.-.V1.docx)
@ron4548

**Comment by ron4548** [comment]
@menhel

**Comment by menhel** [comment]
Nice, I like it!
Now just need to transfer it to HTML format, and add a link in the main menu to it (maybe under ABOUT?)

**Comment by ron4548** [comment]
> Nice, I like it!
> Now just need to transfer it to HTML format, and add a link in the main menu to it (maybe under ABOUT?)

There's already a branch for it, just need to update the content

**Comment by ron4548** [comment]
Updated version of the tutorial will be here, please refer to this version:
https://technionmail-my.sharepoint.com/:w:/g/personal/ron_mar_campus_technion_ac_il/EQhTr74f5m9LhbGooGucnAoBcmt51oDjjWYcftFIgfSJgg?e=MAEuk7

**Comment by ron4548** [comment]
Fixed with #376
