### ISSUE TITLE
Choose our backend technology

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#34]
For the long term, we need to decide whether we will continue to work with Firebase or not. The other option, which requires more development but allows full separation between the backend and the client side is to write a REST API (probably with [Express](https://expressjs.com/) over [NodeJS](https://nodejs.org/en/)). 

Some articles on how to create such a REST API:
https://malcoded.com/posts/angular-backend-express
https://code.tutsplus.com/tutorials/creating-a-blogging-app-using-angular-mongodb-home--cms-30129
https://medium.com/@_aerdeljac/creating-a-rest-api-backend-using-express-js-7710d3310b79

**Comment by ron4548** [comment]
Firebase:
- Fast development
- Easy to use, ready to use services for authentication, storage and database.
- Limited database capabilities
- Client code is written specifically to Firebase

REST:
- We need to write a full API by ourselves that includes authentication and storage capabilities.
- We need to find a hosting for our back-end, I don't believe we will find something free.
- Since we write the API, we are free to use any database technology supported by NodeJS, and we can also change it in the future without changing anything in the client side.
- Once the API is defined, developing the API doesn't require any change to client side code.

**Comment by yuvalron** [comment]
Can you think on a feature that can be implemented using REST but not with firebase?

**Comment by ron4548** [comment]
> Can you think about a feature that can be implemented using REST but not with firebase?

It is not really about Firebase vs REST. It is more about Firebase DB vs other database technologies such as MongoDB or SQL. Maybe @moshesab can give us some insights about which database we should and can use.

**Comment by menhel** [comment]
After discussing this topic with Idan, he recommended us to do the following:
The front end of the website will be in Angular, the beck end will be a REST API written by us (using Express, for example). It will be connected to a DB system (he recommended MongoDB, as FireBase has some lacks in feature support, we discussed it already). 
The main points are:
1. FrontEnd should not connect directly with the DB (otherwise we are allowing visitors in the site do whatever they want to the DB, including erasing it entirely for example).
2. Our BackEnd will define behaviours we allow and will be the only interface to the DB.
3. The DB should allow us to perform various, complicated queries on the data in it, so Mongo should be good for us.

**Comment by ron4548** [comment]
> After discussing this topic with Idan, he recommended us to do the following:
> The front end of the website will be in Angular, the beck end will be a REST API written by us (using Express, for example). It will be connected to a DB system (he recommended MongoDB, as FireBase has some lacks in feature support, we discussed it already).
> The main points are:
> 
> 1. FrontEnd should not connect directly with the DB (otherwise we are allowing visitors in the site do whatever they want to the DB, including erasing it entirely for example).
> 2. Our BackEnd will define behaviours we allow and will be the only interface to the DB.
> 3. The DB should allow us to perform various, complicated queries on the data in it, so Mongo should be good for us.

For now we will keep working with Firebase and do complex logic with cloud functions. In case we declare this project as our main project we will make a better data design and choose our DB accordingly.

**Comment by moshesab** [comment]
We have to test better our need in a DBMS. There are two types of databases: relational and non-relational, each having its pros and cons. 
NoSQL systems (e.g. MongoDB) are great choice if we need scalability and caching for real-time analytics (Supports replication (master/slave), sharding), however, it is not built for transactional data. 
On the other hand maybe we should consider using SQL server (as PostgreSQL) which is is an object-relational database management system with an emphasis on extensibility and standards compliance. It also supports functions and stored procedures. PostgreSQL also supports many NoSQL features as well...

**Comment by ron4548** [comment]
We will go with Firebase
