### ISSUE TITLE
Upload: pages can be selected multiple times

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/Testock#351]
Reproduction:
1. choose a scan to upload
2. start adding pages to any question
3. click on any page to add it to the solution (works fine)
4. click the same page again

Wrong behavior:
The page is selected twice. That is to say it is added twice in the solution (right side menu)

Expected behavior:
The second click should deselect the page.

**Comment by ron4548** [comment]
It's not a bug - clicking the page twice is equivalent to cropping the page twice, and we allow that

**Comment by menhel** [comment]
I disagree. Intuitively, I tried to deselect the page multiple times by clicking it twice, and it frastrated me to see no reaction, only to later see it was added 7 times.
Cropping twice might be OK, although I don't see why the same page should be cropped twice for the same question (I don't believe a user will go through all that trouble just to not include a draft in the middle of the page)
