### ISSUE TITLE
Prepare final presentation

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#354]

**Comment by ron4548** [comment]
Kobi: need to describe future plans (it is possible that a team will work on Testock next year)

**Comment by ron4548** [comment]
Comments from the meeting:
Theortical Background: Which theories we use: Personal Learning, Computer Vision
Architecture: Diagram of the software components (Modules)
Explain about the event we hold
Teamwork: GitHub screen shot, git methodology, CR flow
Firebase: Components and objects
Gamification: Diagram

**Comment by yuvalron** [comment]
No problem

**Comment by yuvalron** [comment]
Link to shared folder:

https://technionmail-my.sharepoint.com/:f:/g/personal/yuval_ron_campus_technion_ac_il/Eo6I8X5QKDRCh2sdYtTsazYBTztAZKJIFqPjKj3-dOpJ1g?e=chsNWW
