### ISSUE TITLE
Remove Faculties Tab?

### ISSUE THREAD

**Issue by yuvalron** [TechnionYP5779/Testock#369]
Since we support only one faculty (CS), is the faculties page not redundant?
@ron4548 @menhel

**Comment by menhel** [comment]
I say, leave it be. Why not?

**Comment by ron4548** [comment]
Leave it be, but there's no doubt it shouldn't be the home page.

**Comment by yuvalron** [comment]
@menhel because it is a list of one item. Once we support another faculty, then it makes sense to have such a page.

**Comment by ron4548** [comment]
> @menhel because it is a list of one item. Once we support another faculty, then it makes sense to have such a page.

I do not agree that we support only CS faculty. We will welcome, and will even post on Facebook, that the Vaad of any other faculty is welcome to contact us and integrate Testock in their faculty..

**Comment by menhel** [comment]
Also, we do support other faculties, which courses CS students take (Infi, physics, MALAG, etc.).

**Comment by ron4548** [comment]
I'm pretty comfort with what we have now. Can this be closed?

**Comment by menhel** [comment]
Fine by me
