### ISSUE TITLE
Chrome plugin: Release and linking

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#370]
Need to release the chrome plugin:
1. Fix it to redirect the user to testock.tk instead of localhost.
2. Upload it to Google Chrome Extensions store.
3. Add links to download it to the website itself, if the user doesn't have the plugin (pretty sure it is easy to add, just look for it in Google)

**Comment by ameeramer** [comment]
where in the website do you think it is best to add the links to download?
