### ISSUE TITLE
Add user's grade input to add question modal

### ISSUE THREAD

**Issue by yuvalron** [TechnionYP5779/Testock#380]
Many users get confused about what is the grade and what is the total grade in the upload interface.

Maybe we should change it to "__ out of __ "

**Comment by ron4548** [comment]
@menhel , do you have any idea? I don't think we have enough place for _ out of _

**Comment by yuvalron** [comment]
I think this is the main problem (in picture). Users think that total grade means their grade.
We should change it to "Total grade (not your grade!):"

![image](https://user-images.githubusercontent.com/19504086/59660867-3a4f6a00-91b2-11e9-844e-d65a3ad70cab.png)

**Comment by ron4548** [comment]
> I think this is the main problem (in picture). Users think that total grade means their grade.
> We should change it to "Total grade (not your grade!):"
> 
> ![image](https://user-images.githubusercontent.com/19504086/59660867-3a4f6a00-91b2-11e9-844e-d65a3ad70cab.png)

If that's the problem then we should add here the user's grade too. I intended to do so, but somehow missed it. Do we agree this issue has to be converted to "Add user's grade input to add question modal"?

**Comment by yuvalron** [comment]
Yes. This is the most logical solution.
