### ISSUE TITLE
Type 'Blob[]' is not assignable to type 'Blob' in upload.component.ts

### ISSUE THREAD

**Issue by yuvalron** [TechnionYP5779/Testock#64]
![image](https://user-images.githubusercontent.com/19504086/50388202-1423a280-0718-11e9-901a-dd62b7964887.png)

**Comment by ron4548** [comment]
Looks like you didn't pull some changes. Check it again.

**Comment by menhel** [comment]
So? Resolved or there is still a bug?
@yuvalron @ron4548

**Comment by yuvalron** [comment]
Strange. I'm working with the latest 'development' version and the bug still exists.

**Comment by ron4548** [comment]
![image](https://user-images.githubusercontent.com/4895877/50398589-62b95700-0781-11e9-84d6-4959dd867e17.png)
Confirm that you have this version of Upload service.

**Comment by yuvalron** [comment]
I restarted Webstorm and the error is gone.
