### ISSUE TITLE
Image Cropper: default size

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/Testock#70]
Set initial size of cropper to be the full size of the image. This is suppose to be done automatically by the ngx-image-cropper component, but for some reason, this is not the case.
It might be a bug in our code, or a bug in the component (in which case we will need to contact the writers of it and let the know).

**Comment by ron4548** [comment]
![image](https://user-images.githubusercontent.com/4895877/50459543-f0a96380-0974-11e9-88d7-0e02b8f3dceb.png)
Seems like it happens because of the modal.

**Comment by ron4548** [comment]
Opened an issue for the developer of ngx-image-cropper. Hope he will cooperate and we will solve it soon :)
https://github.com/Mawi137/ngx-image-cropper/issues/120

**Comment by ron4548** [comment]
The developer of ngx-image-cropper fixed this problem with the assistance of our example. Updated packages for our project to use the new version.
